# export DOCKER_CONFIG=/root/image-mirrors-with-oc-mirror
# oc mirror --config=./production-operator-advanced-cluster-management.yaml docker://production.artifactory.home.local/operators --skip-pruning --skip-missing --skip-cleanup
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  registry:
    imageURL: production.artifactory.home.local/operators
    skipTLS: false
mirror:
  platform:
    architectures:
      - "amd64"
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.14
    packages:
    - name: advanced-cluster-management
      channels:
      - name: release-2.9
    - name: multicluster-engine
      channels:
      - name: stable-2.3