# How to Mirror the compliance Operator to the local file-system
# Copy the content of the pull-secret file to $HOME/.docker/config.json
# oc-mirror uses this credentials file for authentication
# Download to the file-system: 
## oc-mirror --config for-fusion-day-2.yaml file:///root/oc-mirror/for-fusion-day-2-mirror --ignore-history
## oc-mirror --config for-fusion-day-2.yaml file://mirror --ignore-history
# Upload the content from the filesystem to the registry
## oc mirror --from=./mirror_seq1_000000.tar docker://registry.example:5000 
## Optional: oc adm catalog mirror file://redhat/redhat-operator-index:v4.12 REGISTRY/REPOSITORY


# - amq streams 2.6.0-2(stable)
# - Kubernetes nmstate  Operator
# - OpenShift Virtualization 4.12.10(stable)
# - OADP Oeprator 1.3.1 (stable-1.3)

# How to list available operator-images
## oc-mirror list operators --version=4.12 --catalog=registry.redhat.io/redhat/redhat-operator-index:v4.12 --package=amq-streams
## oc-mirror list operators --version=4.12 --catalog=registry.redhat.io/redhat/redhat-operator-index:v4.12 --package=kubernetes-nmstate-operator
## oc-mirror list operators --version=4.12 --catalog=registry.redhat.io/redhat/redhat-operator-index:v4.12 --package=kubevirt-hyperconverged
## oc-mirror list operators --version=4.12 --catalog=registry.redhat.io/redhat/redhat-operator-index:v4.12 --package=redhat-oadp-operator
## oc-mirror list operators --version=4.12 --catalog=registry.redhat.io/redhat/redhat-operator-index:v4.12 --package=compliance-operator
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
mirror:
  platform:
    channels:
    - name: stable-4.13
      minVersion: 4.13.41
      maxVersion: 4.13.41
      type: ocp
    architectures:
      - "amd64"
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.13
    packages:
    # AMQ-Streams Operator
    - name: amq-streams
      channels:
      - name: stable
    # NMSTATE Operator
    - name: kubernetes-nmstate-operator
      channels:
      - name: stable
    # OpenShift Virtualization
    - name: kubevirt-hyperconverged
      channels:
      - name: stable
    # OADP-Operator
    - name: redhat-oadp-operator
      channels:
      - name: stable-1.4
    # Compliance Operator
    - name: compliance-operator
      channels:
      - name: stable
