kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  registry:
    imageURL: patrick-local-docker-repo.artifactory.home.local/mirror/oc-mirror-metadata
    skipTLS: false
mirror:
  platform:
    architectures:
      - "amd64"
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.14
    packages:
    - name: compliance-operator
      channels:
      - name: stable