# export DOCKER_CONFIG=/root/image-mirrors-with-oc-mirror
# oc mirror --config=./imageset-iterative.yaml docker://patrick-local-docker-repo.artifactory.home.local/mirror/oc-mirror-metadata --skip-pruning --skip-missing --skip-cleanup
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  registry:
    imageURL: patrick-local-docker-repo.artifactory.home.local/mirror/oc-mirror-metadata
    skipTLS: false
mirror:
  platform:
    architectures:
      - "amd64"
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.14
    packages:
    # RHACM
    - name: advanced-cluster-management
      channels:
      - name: release-2.9
    - name: multicluster-engine
      channels:
      - name: stable-2.3
    # Compliance Operator
    - name: compliance-operator
      channels:
      - name: stable
    # DevSpaces
    - name: devspaces
      channels:
      - name: stable
    # OpenShift-Data-Foundation
    - name: odf-operator
      channels: 
      - name: stable-4.14
    # GitOps (ArgoCD)
    - name: openshift-gitops-operator
      channels: 
      - name: latest