# export DOCKER_CONFIG=/root/image-mirrors-with-oc-mirror
# oc mirror --config=./production-openshift-414.yaml docker://patrick-local-docker-repo.artifactory.home.local/mirror/oc-mirror-metadata --skip-pruning --skip-missing --skip-cleanup
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  registry:
    imageURL: production.artifactory.home.local/openshift/
    skipTLS: false
mirror:
  platform:
    channels:
    - name: stable-4.14
      type: ocp
