# export DOCKER_CONFIG=/root/image-mirrors-with-oc-mirror
# oc mirror --config=./production-operator-gitops.yaml docker://patrick-local-docker-repo.artifactory.home.local/mirror/oc-mirror-metadata --skip-pruning --skip-missing --skip-cleanup
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  registry:
    imageURL: production.artifactory.home.local/operators/
    skipTLS: false
mirror:
  platform:
    architectures:
      - "amd64"
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.14
    packages:
    # GitOps (ArgoCD)
    - name: openshift-gitops-operator
      channels: 
      - name: latest