# Copy the content of the pull-secret file to
# $HOME/.docker/config.json
# oc-mirror uses this credentials file for authentication

## Download to the file-system:
# oc-mirror --config for-fusion-day-4-15-13.yaml file:///root/oc-mirror/for-fusion-day-4-15-13 --ignore-history
# oc-mirror --config for-fusion-day-4-15-13.yaml file:///root/oc-mirror/for-fusion-day-4-15-13 --skip-pruning --skip-missing --skip -cleanup --ignore-history
# oc-mirror --config for-fusion-day-4-15-13.yaml file:///root/oc-mirror/for-fusion-day-4-15-13 --skip-pruning --skip-missing --skip -cleanup

## Upload the content from the filesystem to the registry
# oc mirror --from=./mirror_seq1_000000.tar docker://patrick.artifactory.home.local/mirror

# How to list available operator-images
## oc-mirror list operators --version=4.15 --catalog=registry.redhat.io/redhat/redhat-operator-index:v4.15 --package=amq-streams
## oc-mirror list operators --version=4.15 --catalog=registry.redhat.io/redhat/redhat-operator-index:v4.15 --package=kubernetes-nmstate-operator
## oc-mirror list operators --version=4.15 --catalog=registry.redhat.io/redhat/redhat-operator-index:v4.15 --package=kubevirt-hyperconverged
## oc-mirror list operators --version=4.15 --catalog=registry.redhat.io/redhat/redhat-operator-index:v4.15 --package=redhat-oadp-operator
## oc-mirror list operators --version=4.15 --catalog=registry.redhat.io/redhat/redhat-operator-index:v4.15 --package=compliance-operator
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
mirror:
  platform:
    channels:
    - name: stable-4.15
      minVersion: 4.15.13
      maxVersion: 4.15.13
      type: ocp
    architectures:
      - "amd64"
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.15
    packages:
    # AMQ-Streams Operator
    - name: amq-streams
      channels:
      - name: stable
    # NMSTATE Operator
    - name: kubernetes-nmstate-operator
      channels:
      - name: stable
    # OpenShift Virtualization
    - name: kubevirt-hyperconverged
      channels:
      - name: stable
    # OADP-Operator
    - name: redhat-oadp-operator
      channels:
      - name: stable-1.4
    # Compliance Operator
    - name: compliance-operator
      channels:
      - name: stable
  # Fusion 2.8.2 Images
  additionalImages:
    - name: cp.icr.io/cp/isf/baas-minio@sha256:07d8b6a01f4bee6a45cedebaa345b1a15f87900f1fb09df52a287d6fcec1cb73
    - name: cp.icr.io/cp/isf/callhomeclient@sha256:3033a35c94ae4368cf399f06297729357065a512adac23782a732c78b43fafe7
    - name: cp.icr.io/cp/isf/eventmanager-snmp3@sha256:b723baeb223d4e50b6870d79847f4f43af883297236782f978791509614466ba
    - name: cp.icr.io/cp/isf/eventmanager@sha256:8021f5fe28ae0def1b5ac259ba06564062b1876d4c05e0ec6329dce726b86a98
    - name: cp.icr.io/cp/isf/fusion-ui@sha256:69172f5ff1c2d845b7a9c0142cbe3dc21c46cc6bcf0f5ae8e8313d0e0cbd1d46
    - name: cp.icr.io/cp/isf/isf-application-operator@sha256:10ec9856edef1d9daeed7302bbdd6b304c7539a7003e24b2c7187ab08fdb5211
    - name: cp.icr.io/cp/isf/isf-cns-operator@sha256:803805eb1bcb695a8f3efc6085fe65f0e1c7c81a76d781ae2e86f2ca87aba109
    - name: cp.icr.io/cp/isf/isf-compute-fw-updater@sha256:7875e65ef268a355d6889c0a27a71b0f967a8da1ccbfc9050e83201776860f71
    - name: cp.icr.io/cp/isf/isf-compute-operator@sha256:6fa08b844e396064cb5e22c2ba0def166796099b9b8c8fdc4a8e769a7ea7cc22
    - name: cp.icr.io/cp/isf/isf-data-protection-operator@sha256:4696704fba77b4e74d86958debc1a0d5571acccf52fb14cd3be11fcb103e5664
    - name: cp.icr.io/cp/isf/isf-hcp-manager@sha256:ca585db2880101d8492edfd0b153c07bd90aaf7f24a955a7fa8907c31be10eaa
    - name: cp.icr.io/cp/isf/isf-ics-operator@sha256:dab248995499264e9d709b48470beb0cf05ae822dd7b544afbc2f1168cf8b84d
    - name: cp.icr.io/cp/isf/isf-management-consoleplugin@sha256:8b0329187fabcacf2d827c5339daa6052b64ab94d0201ebbcf8c231206d8df80
    - name: cp.icr.io/cp/isf/isf-metrodr-operator@sha256:e66dc07f671217bcff0da2716b60048e0170decd491bb1c84bd6b428a950a00b
    - name: cp.icr.io/cp/isf/isf-network-fw-updater@sha256:a595dcb4b0e024d3d2897cd128eb8d2e3886f71a693fa5534721b554950cf8d2
    - name: cp.icr.io/cp/isf/isf-network-operator@sha256:658aa2be795693aa9baadffa915602afa293ef751895325e86d54945066c5daf
    - name: cp.icr.io/cp/isf/isf-node-exporter@sha256:03c50732369b82394c2053507c18e08633564e865d1814ef4ea3b8a32e2c35ea
    - name: cp.icr.io/cp/isf/isf-prereq-operator@sha256:ee61b2d93b7accbed654b176293b4aa50f2758a26f1912c55a67c81b2fd3571d
    - name: cp.icr.io/cp/isf/isf-proxy@sha256:4c949649c9ed64ebf2f614802a69ec5a3d2c74d75522b2cf3e403abc98f65a17
    - name: cp.icr.io/cp/isf/isf-serviceability-operator@sha256:2d75cd1c3950318f8b39da591e1f943ffba9b72d0b889d4803fb47132c55a5de
    - name: cp.icr.io/cp/isf/isf-snmp-exporter@sha256:3406d95eb431e359c281554fcb5456a14dd2335cebcec417815dbe7a50c950b3
    - name: cp.icr.io/cp/isf/isf-storage-operator@sha256:def78a2ee68feaa6b4a6e6ca9882432beb97b8e1fecacda54708a6ac78a1a748
    - name: cp.icr.io/cp/isf/isf-storage-services@sha256:911fb7b6e6229972fce8c89ac2423be1dc1bf9128b609a5e3827301d141e346b
    - name: cp.icr.io/cp/isf/isf-ui-operator@sha256:e7a83426767f8cb6e4c839730cd6c7c174af7d8d71e2572df37838a2c8e680b6
    - name: cp.icr.io/cp/isf/isf-update-operator@sha256:c72f91393053347802c7e3957440572ab1179c94805cd680eea8c8ade0a08ddd
    - name: cp.icr.io/cp/isf/isf-utils@sha256:8a969b6225cf87080879ba558175d90a36559bdb2accfb77e2285958e088d69c
    - name: cp.icr.io/cp/isf/isf-validate-entitlement@sha256:1a0dbf7c537f02dc0091e3abebae0ccac83da6aa147529f5de49af0f23cd9e8e
    - name: cp.icr.io/cp/isf/logcollector@sha256:7621c8b14baab622013db02731f29fea2c4ce63c02c5d79fbd26ff6cd112f01f
    - name: cp.icr.io/cp/isf/ramen-operator@sha256:23df6a572f2dab286e7a6189303079adb07b075f975469442e605c834ac9bfac
    - name: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
    - name: icr.io/cpopen/isf-operator-bundle@sha256:30174fd0717284179b2d4aef2949a0daf9f5a97ef5622cfecfc050cd891075fc
    - name: icr.io/cpopen/isf-operator-catalog:2.8.2-linux.amd64
    - name: quay.io/submariner/lighthouse-agent:0.16.3
    - name: quay.io/submariner/lighthouse-coredns:0.16.3
    - name: quay.io/submariner/nettest:0.16.3
    - name: quay.io/submariner/submariner-gateway:0.16.3
    - name: quay.io/submariner/submariner-operator:0.16.3
    - name: quay.io/submariner/submariner-route-agent:0.16.3
    - name: registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:767682dd3bd65651a8204c9fb732b9c48b99127189992b43abc6ecce027f4589
